---
- name: Provision Windows VM from Azure Compute Gallery
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - azure.azcollection
  vars_files:
    - vault.yml    

  vars:
    resource_group: "RG_INFRA"
    location: "eastus"
    vnet_name: "VNET_GENERIC"
#    vm_name: winvm-from-gallery
    vm_size: Standard_B1s
    admin_username: azureuser
    admin_password: "{{ admin_password }}"
    subnet_name: SUBNET_APP
#    nic_name: winvm-nic
#    public_ip_name: winvm-pip
    image_gallery: Ana_Gallery2
    image_definition: Win2022G2
    image_version: 1.0.0   

  tasks:
    - name: Get Shared Image Gallery version info
      azure.azcollection.azure_rm_galleryimageversion_info:
        resource_group: "{{ resource_group }}"
        gallery_name: "{{ image_gallery }}"
        gallery_image_name: "{{ image_definition }}"
        name: "{{ image_version }}"
      register: gallery_version_info

    - debug:
        var: gallery_version_info.versions   

    - name: Generate NIC name
      set_fact:
        nic_name: "{{ vm_name }}_nic"

    - debug:
        msg: "Using NIC name: {{ nic_name }}"    

    - name: Create network interface
      azure_rm_networkinterface:
        resource_group: "RG_NETWORK"
        name: "{{ nic_name }}"
        location: "{{ location }}"
        #subnet: "{{ subnet_name }}"
        virtual_network_name: "{{ vnet_name }}"   
        ip_configurations:
          - name: ipconfig1
        subnet:
          id: "/subscriptions/3d489bb7-7b50-4375-93ca-5e42db0494e1/resourceGroups/RG_NETWORK/providers/Microsoft.Network/virtualNetworks/VNET_GENERIC/subnets/SUBNET_APP"        

    - name: Provision Windows VM
      azure_rm_virtualmachine:
        name: "{{ vm_name }}"
        resource_group: "{{ resource_group }}"
        location: "{{ location }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        # virtual_network_name: "{{ vnet_name }}"
        # subnet: "{{ subnet_name }}"
        network_interfaces: "{{ nic_name }}"
        os_type: Windows
        image:        
          # id: "/subscriptions/3d489bb7-7b50-4375-93ca-5e42db0494e1/resourceGroups/winImageBuildRG/providers/Microsoft.Compute/galleries/Ana_Gallery/images/Win2022Datacenter/versions/1.0.0"
          id: "{{ gallery_version_info.versions[0].id }}"
        custom_data: "{{ lookup('file', 'enable_winrm.ps1') | b64encode }}"
        managed_disk_type: Standard_LRS
        security_profile:
          security_type: TrustedLaunch
          uefi_settings:
            secure_boot_enabled: true
            v_tpm_enabled: true
        state: present
